### PR TITLE
Code improvement

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
BTW, you only prevent him to _hold_ diamonds, which is useless if you don't prevent him to _use_ diamonds in other ways, e.g. crafting, saving into chests, etc.

**Comment by seanmcpe** [comment]
I know. :p 
How do I make it so he can't do that? I didn't know how.

**Comment by PEMapModder** [comment]
Maybe prevent him from even getting it?

**Comment by seanmcpe** [comment]
Hmm, I guess. How though? When it goes in his inventory kick?

**Comment by PEMapModder** [comment]
Try hooking to `InventoryTransactionEvent`, loop over `$event->getTransactions()->getTransactions()`, and if the transaction's `getTargetItem()->getId()` is the diamond ID, cancel event and kick?

**Comment by seanmcpe** [comment]
Okay.

**Pull request merged**
